//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class CoreService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    branchPOST(body: CreateBranchDto | undefined): Observable<GetBranchDtoBaseResponse> {
        let url_ = this.baseUrl + "/Branch";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBranchPOST(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBranchPOST(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetBranchDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetBranchDtoBaseResponse>;
        }));
    }

    protected processBranchPOST(response: HttpResponseBase): Observable<GetBranchDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetBranchDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    branchGET(): Observable<GetBranchDtoListBaseResponse> {
        let url_ = this.baseUrl + "/Branch";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBranchGET(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBranchGET(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetBranchDtoListBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetBranchDtoListBaseResponse>;
        }));
    }

    protected processBranchGET(response: HttpResponseBase): Observable<GetBranchDtoListBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetBranchDtoListBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    branchGET2(id: number): Observable<GetBranchDtoBaseResponse> {
        let url_ = this.baseUrl + "/Branch/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBranchGET2(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBranchGET2(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetBranchDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetBranchDtoBaseResponse>;
        }));
    }

    protected processBranchGET2(response: HttpResponseBase): Observable<GetBranchDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetBranchDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    branchPUT(id: number, body: CreateBranchDto | undefined): Observable<GetBranchDtoBaseResponse> {
        let url_ = this.baseUrl + "/Branch/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBranchPUT(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBranchPUT(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetBranchDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetBranchDtoBaseResponse>;
        }));
    }

    protected processBranchPUT(response: HttpResponseBase): Observable<GetBranchDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetBranchDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    branchDELETE(id: number): Observable<BooleanBaseResponse> {
        let url_ = this.baseUrl + "/Branch/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBranchDELETE(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBranchDELETE(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BooleanBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BooleanBaseResponse>;
        }));
    }

    protected processBranchDELETE(response: HttpResponseBase): Observable<BooleanBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BooleanBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getFacilities(): Observable<FacilityDtoListBaseResponse> {
        let url_ = this.baseUrl + "/Facility/GetFacilities";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetFacilities(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetFacilities(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FacilityDtoListBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FacilityDtoListBaseResponse>;
        }));
    }

    protected processGetFacilities(response: HttpResponseBase): Observable<FacilityDtoListBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FacilityDtoListBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getFacility(id: number): Observable<FacilityDtoBaseResponse> {
        let url_ = this.baseUrl + "/Facility/GetFacility/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetFacility(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetFacility(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FacilityDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FacilityDtoBaseResponse>;
        }));
    }

    protected processGetFacility(response: HttpResponseBase): Observable<FacilityDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FacilityDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createFacility(body: CreateFacilityDto | undefined): Observable<FacilityDtoBaseResponse> {
        let url_ = this.baseUrl + "/Facility/CreateFacility";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateFacility(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateFacility(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FacilityDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FacilityDtoBaseResponse>;
        }));
    }

    protected processCreateFacility(response: HttpResponseBase): Observable<FacilityDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FacilityDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateFacility(id: number, body: FacilityDto | undefined): Observable<FacilityDtoBaseResponse> {
        let url_ = this.baseUrl + "/Facility/UpdateFacility/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateFacility(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateFacility(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FacilityDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FacilityDtoBaseResponse>;
        }));
    }

    protected processUpdateFacility(response: HttpResponseBase): Observable<FacilityDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FacilityDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    facility(id: number): Observable<BooleanBaseResponse> {
        let url_ = this.baseUrl + "/Facility/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processFacility(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processFacility(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BooleanBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BooleanBaseResponse>;
        }));
    }

    protected processFacility(response: HttpResponseBase): Observable<BooleanBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BooleanBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getPackages(): Observable<GetPackageDtoListBaseResponse> {
        let url_ = this.baseUrl + "/Package/GetPackages";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPackages(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPackages(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetPackageDtoListBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetPackageDtoListBaseResponse>;
        }));
    }

    protected processGetPackages(response: HttpResponseBase): Observable<GetPackageDtoListBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetPackageDtoListBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createPackage(body: AddPackageDto | undefined): Observable<StringBaseResponse> {
        let url_ = this.baseUrl + "/Package/CreatePackage";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreatePackage(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreatePackage(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringBaseResponse>;
        }));
    }

    protected processCreatePackage(response: HttpResponseBase): Observable<StringBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StringBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updatePackage(id: number, body: AddPackageDto | undefined): Observable<StringBaseResponse> {
        let url_ = this.baseUrl + "/Package/UpdatePackage/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdatePackage(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdatePackage(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringBaseResponse>;
        }));
    }

    protected processUpdatePackage(response: HttpResponseBase): Observable<StringBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StringBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    deletePackage(id: number): Observable<StringBaseResponse> {
        let url_ = this.baseUrl + "/Package/DeletePackage/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeletePackage(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeletePackage(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringBaseResponse>;
        }));
    }

    protected processDeletePackage(response: HttpResponseBase): Observable<StringBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StringBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getPackage(id: number): Observable<GetPackageDtoBaseResponse> {
        let url_ = this.baseUrl + "/Package/GetPackage/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPackage(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPackage(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetPackageDtoBaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetPackageDtoBaseResponse>;
        }));
    }

    protected processGetPackage(response: HttpResponseBase): Observable<GetPackageDtoBaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetPackageDtoBaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return OK
     */
    getWeatherForecast(): Observable<WeatherForecast[]> {
        let url_ = this.baseUrl + "/WeatherForecast";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetWeatherForecast(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetWeatherForecast(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<WeatherForecast[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<WeatherForecast[]>;
        }));
    }

    protected processGetWeatherForecast(response: HttpResponseBase): Observable<WeatherForecast[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WeatherForecast.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class AddPackageDto implements IAddPackageDto {
    name?: string | undefined;
    description?: string | undefined;
    defaultDiscount?: number;
    writtenServices?: string | undefined;
    maxBranchUsers?: number;
    maxMogdiPlatformUsage?: number;
    packageFacilities?: AddPackageFacilityDto[] | undefined;

    constructor(data?: IAddPackageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.defaultDiscount = _data["defaultDiscount"];
            this.writtenServices = _data["writtenServices"];
            this.maxBranchUsers = _data["maxBranchUsers"];
            this.maxMogdiPlatformUsage = _data["maxMogdiPlatformUsage"];
            if (Array.isArray(_data["packageFacilities"])) {
                this.packageFacilities = [] as any;
                for (let item of _data["packageFacilities"])
                    this.packageFacilities!.push(AddPackageFacilityDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): AddPackageDto {
        data = typeof data === 'object' ? data : {};
        let result = new AddPackageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["defaultDiscount"] = this.defaultDiscount;
        data["writtenServices"] = this.writtenServices;
        data["maxBranchUsers"] = this.maxBranchUsers;
        data["maxMogdiPlatformUsage"] = this.maxMogdiPlatformUsage;
        if (Array.isArray(this.packageFacilities)) {
            data["packageFacilities"] = [];
            for (let item of this.packageFacilities)
                data["packageFacilities"].push(item.toJSON());
        }
        return data;
    }
}

export interface IAddPackageDto {
    name?: string | undefined;
    description?: string | undefined;
    defaultDiscount?: number;
    writtenServices?: string | undefined;
    maxBranchUsers?: number;
    maxMogdiPlatformUsage?: number;
    packageFacilities?: AddPackageFacilityDto[] | undefined;
}

export class AddPackageFacilityDto implements IAddPackageFacilityDto {
    packageId?: number;
    facilityId?: number;
    typeId?: number;
    quantity?: number;
    percentageDicount?: number;
    price?: number;
    isTaxIncluded?: boolean;

    constructor(data?: IAddPackageFacilityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.packageId = _data["packageId"];
            this.facilityId = _data["facilityId"];
            this.typeId = _data["typeId"];
            this.quantity = _data["quantity"];
            this.percentageDicount = _data["percentageDicount"];
            this.price = _data["price"];
            this.isTaxIncluded = _data["isTaxIncluded"];
        }
    }

    static fromJS(data: any): AddPackageFacilityDto {
        data = typeof data === 'object' ? data : {};
        let result = new AddPackageFacilityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["packageId"] = this.packageId;
        data["facilityId"] = this.facilityId;
        data["typeId"] = this.typeId;
        data["quantity"] = this.quantity;
        data["percentageDicount"] = this.percentageDicount;
        data["price"] = this.price;
        data["isTaxIncluded"] = this.isTaxIncluded;
        return data;
    }
}

export interface IAddPackageFacilityDto {
    packageId?: number;
    facilityId?: number;
    typeId?: number;
    quantity?: number;
    percentageDicount?: number;
    price?: number;
    isTaxIncluded?: boolean;
}

export class BooleanBaseResponse implements IBooleanBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: boolean;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IBooleanBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            this.responseData = _data["responseData"];
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): BooleanBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BooleanBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        data["responseData"] = this.responseData;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IBooleanBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: boolean;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class CreateBranchComponentDto implements ICreateBranchComponentDto {
    branchId?: number;
    componentId?: number;

    constructor(data?: ICreateBranchComponentDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.branchId = _data["branchId"];
            this.componentId = _data["componentId"];
        }
    }

    static fromJS(data: any): CreateBranchComponentDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateBranchComponentDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["branchId"] = this.branchId;
        data["componentId"] = this.componentId;
        return data;
    }
}

export interface ICreateBranchComponentDto {
    branchId?: number;
    componentId?: number;
}

export class CreateBranchDto implements ICreateBranchDto {
    name?: string | undefined;
    websiteBranchId?: number;
    workingDays?: string | undefined;
    startTime?: Date;
    endTime?: Date;
    categoryBranchId?: number;
    branchComponents?: CreateBranchComponentDto[] | undefined;

    constructor(data?: ICreateBranchDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.websiteBranchId = _data["websiteBranchId"];
            this.workingDays = _data["workingDays"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.categoryBranchId = _data["categoryBranchId"];
            if (Array.isArray(_data["branchComponents"])) {
                this.branchComponents = [] as any;
                for (let item of _data["branchComponents"])
                    this.branchComponents!.push(CreateBranchComponentDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateBranchDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateBranchDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["websiteBranchId"] = this.websiteBranchId;
        data["workingDays"] = this.workingDays;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["categoryBranchId"] = this.categoryBranchId;
        if (Array.isArray(this.branchComponents)) {
            data["branchComponents"] = [];
            for (let item of this.branchComponents)
                data["branchComponents"].push(item.toJSON());
        }
        return data;
    }
}

export interface ICreateBranchDto {
    name?: string | undefined;
    websiteBranchId?: number;
    workingDays?: string | undefined;
    startTime?: Date;
    endTime?: Date;
    categoryBranchId?: number;
    branchComponents?: CreateBranchComponentDto[] | undefined;
}

export class CreateFacilityDto implements ICreateFacilityDto {
    name?: string | undefined;
    categoryId?: number | undefined;
    typeId?: number | undefined;
    destinationId?: number | undefined;
    pricingUnitId?: number | undefined;
    subscriptionId?: number | undefined;
    basePrice?: number;
    isTaxIncluded?: boolean;
    basicContract?: number;
    isPublish?: boolean;

    constructor(data?: ICreateFacilityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.categoryId = _data["categoryId"];
            this.typeId = _data["typeId"];
            this.destinationId = _data["destinationId"];
            this.pricingUnitId = _data["pricingUnitId"];
            this.subscriptionId = _data["subscriptionId"];
            this.basePrice = _data["basePrice"];
            this.isTaxIncluded = _data["isTaxIncluded"];
            this.basicContract = _data["basicContract"];
            this.isPublish = _data["isPublish"];
        }
    }

    static fromJS(data: any): CreateFacilityDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateFacilityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["categoryId"] = this.categoryId;
        data["typeId"] = this.typeId;
        data["destinationId"] = this.destinationId;
        data["pricingUnitId"] = this.pricingUnitId;
        data["subscriptionId"] = this.subscriptionId;
        data["basePrice"] = this.basePrice;
        data["isTaxIncluded"] = this.isTaxIncluded;
        data["basicContract"] = this.basicContract;
        data["isPublish"] = this.isPublish;
        return data;
    }
}

export interface ICreateFacilityDto {
    name?: string | undefined;
    categoryId?: number | undefined;
    typeId?: number | undefined;
    destinationId?: number | undefined;
    pricingUnitId?: number | undefined;
    subscriptionId?: number | undefined;
    basePrice?: number;
    isTaxIncluded?: boolean;
    basicContract?: number;
    isPublish?: boolean;
}

export class Errors implements IErrors {
    key?: number;
    value?: string | undefined;

    constructor(data?: IErrors) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): Errors {
        data = typeof data === 'object' ? data : {};
        let result = new Errors();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key;
        data["value"] = this.value;
        return data;
    }
}

export interface IErrors {
    key?: number;
    value?: string | undefined;
}

export class FacilityDto implements IFacilityDto {
    id?: number;
    name?: string | undefined;
    categoryName?: string | undefined;
    typeName?: string | undefined;
    destinationName?: string | undefined;
    pricingUnitName?: string | undefined;
    subscriptionName?: string | undefined;
    basePrice?: number;
    isTaxIncluded?: boolean;
    basicContract?: number;
    isPublish?: boolean;

    constructor(data?: IFacilityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.categoryName = _data["categoryName"];
            this.typeName = _data["typeName"];
            this.destinationName = _data["destinationName"];
            this.pricingUnitName = _data["pricingUnitName"];
            this.subscriptionName = _data["subscriptionName"];
            this.basePrice = _data["basePrice"];
            this.isTaxIncluded = _data["isTaxIncluded"];
            this.basicContract = _data["basicContract"];
            this.isPublish = _data["isPublish"];
        }
    }

    static fromJS(data: any): FacilityDto {
        data = typeof data === 'object' ? data : {};
        let result = new FacilityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["categoryName"] = this.categoryName;
        data["typeName"] = this.typeName;
        data["destinationName"] = this.destinationName;
        data["pricingUnitName"] = this.pricingUnitName;
        data["subscriptionName"] = this.subscriptionName;
        data["basePrice"] = this.basePrice;
        data["isTaxIncluded"] = this.isTaxIncluded;
        data["basicContract"] = this.basicContract;
        data["isPublish"] = this.isPublish;
        return data;
    }
}

export interface IFacilityDto {
    id?: number;
    name?: string | undefined;
    categoryName?: string | undefined;
    typeName?: string | undefined;
    destinationName?: string | undefined;
    pricingUnitName?: string | undefined;
    subscriptionName?: string | undefined;
    basePrice?: number;
    isTaxIncluded?: boolean;
    basicContract?: number;
    isPublish?: boolean;
}

export class FacilityDtoBaseResponse implements IFacilityDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: FacilityDto;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IFacilityDtoBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            this.responseData = _data["responseData"] ? FacilityDto.fromJS(_data["responseData"]) : <any>undefined;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): FacilityDtoBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new FacilityDtoBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        data["responseData"] = this.responseData ? this.responseData.toJSON() : <any>undefined;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IFacilityDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: FacilityDto;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class FacilityDtoListBaseResponse implements IFacilityDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: FacilityDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IFacilityDtoListBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            if (Array.isArray(_data["responseData"])) {
                this.responseData = [] as any;
                for (let item of _data["responseData"])
                    this.responseData!.push(FacilityDto.fromJS(item));
            }
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): FacilityDtoListBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new FacilityDtoListBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        if (Array.isArray(this.responseData)) {
            data["responseData"] = [];
            for (let item of this.responseData)
                data["responseData"].push(item.toJSON());
        }
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IFacilityDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: FacilityDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class GetBranchComponentDto implements IGetBranchComponentDto {
    id?: number;
    branchName?: string | undefined;
    componentName?: string | undefined;

    constructor(data?: IGetBranchComponentDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.branchName = _data["branchName"];
            this.componentName = _data["componentName"];
        }
    }

    static fromJS(data: any): GetBranchComponentDto {
        data = typeof data === 'object' ? data : {};
        let result = new GetBranchComponentDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["branchName"] = this.branchName;
        data["componentName"] = this.componentName;
        return data;
    }
}

export interface IGetBranchComponentDto {
    id?: number;
    branchName?: string | undefined;
    componentName?: string | undefined;
}

export class GetBranchDto implements IGetBranchDto {
    id?: number;
    name?: string | undefined;
    websiteBranchId?: number;
    workingDays?: string | undefined;
    startTime?: Date;
    endTime?: Date;
    categoryBranchId?: number;
    branchComponents?: GetBranchComponentDto[] | undefined;

    constructor(data?: IGetBranchDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.websiteBranchId = _data["websiteBranchId"];
            this.workingDays = _data["workingDays"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.categoryBranchId = _data["categoryBranchId"];
            if (Array.isArray(_data["branchComponents"])) {
                this.branchComponents = [] as any;
                for (let item of _data["branchComponents"])
                    this.branchComponents!.push(GetBranchComponentDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetBranchDto {
        data = typeof data === 'object' ? data : {};
        let result = new GetBranchDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["websiteBranchId"] = this.websiteBranchId;
        data["workingDays"] = this.workingDays;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["categoryBranchId"] = this.categoryBranchId;
        if (Array.isArray(this.branchComponents)) {
            data["branchComponents"] = [];
            for (let item of this.branchComponents)
                data["branchComponents"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGetBranchDto {
    id?: number;
    name?: string | undefined;
    websiteBranchId?: number;
    workingDays?: string | undefined;
    startTime?: Date;
    endTime?: Date;
    categoryBranchId?: number;
    branchComponents?: GetBranchComponentDto[] | undefined;
}

export class GetBranchDtoBaseResponse implements IGetBranchDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetBranchDto;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IGetBranchDtoBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            this.responseData = _data["responseData"] ? GetBranchDto.fromJS(_data["responseData"]) : <any>undefined;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): GetBranchDtoBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetBranchDtoBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        data["responseData"] = this.responseData ? this.responseData.toJSON() : <any>undefined;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IGetBranchDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetBranchDto;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class GetBranchDtoListBaseResponse implements IGetBranchDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetBranchDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IGetBranchDtoListBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            if (Array.isArray(_data["responseData"])) {
                this.responseData = [] as any;
                for (let item of _data["responseData"])
                    this.responseData!.push(GetBranchDto.fromJS(item));
            }
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): GetBranchDtoListBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetBranchDtoListBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        if (Array.isArray(this.responseData)) {
            data["responseData"] = [];
            for (let item of this.responseData)
                data["responseData"].push(item.toJSON());
        }
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IGetBranchDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetBranchDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class GetPackageDto implements IGetPackageDto {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    defaultDiscount?: number;
    writtenServices?: string | undefined;
    maxBranchUsers?: number;
    maxMogdiPlatformUsage?: number;
    packageFacilities?: GetPackageFacilityDto[] | undefined;

    constructor(data?: IGetPackageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.defaultDiscount = _data["defaultDiscount"];
            this.writtenServices = _data["writtenServices"];
            this.maxBranchUsers = _data["maxBranchUsers"];
            this.maxMogdiPlatformUsage = _data["maxMogdiPlatformUsage"];
            if (Array.isArray(_data["packageFacilities"])) {
                this.packageFacilities = [] as any;
                for (let item of _data["packageFacilities"])
                    this.packageFacilities!.push(GetPackageFacilityDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetPackageDto {
        data = typeof data === 'object' ? data : {};
        let result = new GetPackageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["defaultDiscount"] = this.defaultDiscount;
        data["writtenServices"] = this.writtenServices;
        data["maxBranchUsers"] = this.maxBranchUsers;
        data["maxMogdiPlatformUsage"] = this.maxMogdiPlatformUsage;
        if (Array.isArray(this.packageFacilities)) {
            data["packageFacilities"] = [];
            for (let item of this.packageFacilities)
                data["packageFacilities"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGetPackageDto {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    defaultDiscount?: number;
    writtenServices?: string | undefined;
    maxBranchUsers?: number;
    maxMogdiPlatformUsage?: number;
    packageFacilities?: GetPackageFacilityDto[] | undefined;
}

export class GetPackageDtoBaseResponse implements IGetPackageDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetPackageDto;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IGetPackageDtoBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            this.responseData = _data["responseData"] ? GetPackageDto.fromJS(_data["responseData"]) : <any>undefined;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): GetPackageDtoBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetPackageDtoBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        data["responseData"] = this.responseData ? this.responseData.toJSON() : <any>undefined;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IGetPackageDtoBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetPackageDto;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class GetPackageDtoListBaseResponse implements IGetPackageDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetPackageDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IGetPackageDtoListBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            if (Array.isArray(_data["responseData"])) {
                this.responseData = [] as any;
                for (let item of _data["responseData"])
                    this.responseData!.push(GetPackageDto.fromJS(item));
            }
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): GetPackageDtoListBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetPackageDtoListBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        if (Array.isArray(this.responseData)) {
            data["responseData"] = [];
            for (let item of this.responseData)
                data["responseData"].push(item.toJSON());
        }
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IGetPackageDtoListBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: GetPackageDto[] | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class GetPackageFacilityDto implements IGetPackageFacilityDto {
    id?: number;
    packageName?: string | undefined;
    facilityName?: string | undefined;
    typeName?: string | undefined;
    quantity?: number;
    percentageDicount?: number;
    price?: number;
    isTaxIncluded?: boolean;

    constructor(data?: IGetPackageFacilityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.packageName = _data["packageName"];
            this.facilityName = _data["facilityName"];
            this.typeName = _data["typeName"];
            this.quantity = _data["quantity"];
            this.percentageDicount = _data["percentageDicount"];
            this.price = _data["price"];
            this.isTaxIncluded = _data["isTaxIncluded"];
        }
    }

    static fromJS(data: any): GetPackageFacilityDto {
        data = typeof data === 'object' ? data : {};
        let result = new GetPackageFacilityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["packageName"] = this.packageName;
        data["facilityName"] = this.facilityName;
        data["typeName"] = this.typeName;
        data["quantity"] = this.quantity;
        data["percentageDicount"] = this.percentageDicount;
        data["price"] = this.price;
        data["isTaxIncluded"] = this.isTaxIncluded;
        return data;
    }
}

export interface IGetPackageFacilityDto {
    id?: number;
    packageName?: string | undefined;
    facilityName?: string | undefined;
    typeName?: string | undefined;
    quantity?: number;
    percentageDicount?: number;
    price?: number;
    isTaxIncluded?: boolean;
}

export class StringBaseResponse implements IStringBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: string | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;

    constructor(data?: IStringBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.version = _data["version"];
            this.message = _data["message"];
            this.responseData = _data["responseData"];
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(Errors.fromJS(item));
            }
            this.statusCode = _data["statusCode"];
        }
    }

    static fromJS(data: any): StringBaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new StringBaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["version"] = this.version;
        data["message"] = this.message;
        data["responseData"] = this.responseData;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item.toJSON());
        }
        data["statusCode"] = this.statusCode;
        return data;
    }
}

export interface IStringBaseResponse {
    isSuccess?: boolean;
    version?: number;
    message?: string | undefined;
    responseData?: string | undefined;
    errors?: Errors[] | undefined;
    statusCode?: number;
}

export class WeatherForecast implements IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: string | undefined;

    constructor(data?: IWeatherForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.temperatureC = _data["temperatureC"];
            (<any>this).temperatureF = _data["temperatureF"];
            this.summary = _data["summary"];
        }
    }

    static fromJS(data: any): WeatherForecast {
        data = typeof data === 'object' ? data : {};
        let result = new WeatherForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["temperatureC"] = this.temperatureC;
        data["temperatureF"] = this.temperatureF;
        data["summary"] = this.summary;
        return data;
    }
}

export interface IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | undefined;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}